#!/usr/bin/env bash
# Does the following:
#   Create a file /var/run/myscript.pid containing the script PID.
#   Displays "To infinity and beyond" indefinitely
#   Displays "I hate the kill command" upon receiving a SIGTERM
#   Displays "Y U no love me?!" upon receiving a SIGINT
#   Deletes the file /var/run/myscript.pid and terminates upon
#+  receiving a SIGQUIT or SIGTERM.

mkdir -p var/run && touch var/run/myscript.pid

pgrep -f myscript.pid > var/run/myscript.pid

terminator() {
  rm ./var/run/myscript.pid
  exit
}

  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT

while true
do
  echo "To infinity and beyond"
  sleep 2
done
