#!/usr/bin/env bash
# Displays files info about file status of `school`
FILE=school
if test -e "$FILE"; then
    echo $FILE 'school file exists'
    if test -s "$FILE"; then  # size > 0 / not empty
	echo $FILE 'school file is not empty'
    else
	echo $FILE 'school file is empty'
    fi
    if test -f "$FILE"; then  # regular file
	echo $FILE 'school is a regular file'
    fi
else
    echo $FILE 'school file does not exist'
fi
